package main

import (
  "fmt"
  "strings"
)

type Coord struct {
  x,y int
}

func main() {
  instructions := strings.Split(input, "\n")
  buttons := make(map[Coord]string)
  buttons[Coord{2,0}] = "5"
  buttons[Coord{2,1}] = "6"
  buttons[Coord{2,2}] = "7"
  buttons[Coord{2,3}] = "8"
  buttons[Coord{2,4}] = "9"

  buttons[Coord{0,0}] = "#"
  buttons[Coord{0,1}] = "#"
  buttons[Coord{0,2}] = "1"
  buttons[Coord{0,3}] = "#"
  buttons[Coord{0,4}] = "#"

  buttons[Coord{1,0}] = "#"
  buttons[Coord{1,1}] = "2"
  buttons[Coord{1,2}] = "3"
  buttons[Coord{1,3}] = "4"
  buttons[Coord{1,4}] = "#"

  buttons[Coord{3,0}] = "#"
  buttons[Coord{3,1}] = "A"
  buttons[Coord{3,2}] = "B"
  buttons[Coord{3,3}] = "C"
  buttons[Coord{3,4}] = "#"

  buttons[Coord{4,0}] = "#"
  buttons[Coord{4,1}] = "#"
  buttons[Coord{4,2}] = "D"
  buttons[Coord{4,3}] = "#"
  buttons[Coord{4,4}] = "#"

  directions := make(map[rune]Coord)
  directions[rune('U')] = Coord{-1,0}
  directions[rune('L')] = Coord{0,-1}
  directions[rune('R')] = Coord{0,1}
  directions[rune('D')] = Coord{1,0}

  //res := make([]Coord, 0)
  button := Coord{2,2}

  take_step := func(button, step Coord) Coord {
    x, y := button.x + step.x, button.y + step.y
    if x < 0 || x > 4 || y < 0 || y > 4 {
      return button
    } else if buttons[Coord{x,y}] == "#" {
      return button
    } else {
      return Coord{x,y}
    }
  }

  for _, instruction := range instructions {
    for _, step := range instruction {
      button = take_step(button, directions[step])
    }
    fmt.Println(buttons[button])
  }
}

var input = `DUURRDRRURUUUDLRUDDLLLURULRRLDULDRDUULULLUUUDRDUDDURRULDRDDDUDDURLDLLDDRRURRUUUDDRUDDLLDDDURLRDDDULRDUDDRDRLRDUULDLDRDLUDDDLRDRLDLUUUDLRDLRUUUDDLUURRLLLUUUUDDLDRRDRDRLDRLUUDUDLDRUDDUDLLUUURUUDLULRDRULURURDLDLLDLLDUDLDRDULLDUDDURRDDLLRLLLLDLDRLDDUULRDRURUDRRRDDDUULRULDDLRLLLLRLLLLRLURRRLRLRDLULRRLDRULDRRLRURDDLDDRLRDLDRLULLRRUDUURRULLLRLRLRRUDLRDDLLRRUDUDUURRRDRDLDRUDLDRDLUUULDLRLLDRULRULLRLRDRRLRLULLRURUULRLLRRRDRLULUDDUUULDULDUDDDUDLRLLRDRDLUDLRLRRDDDURUUUDULDLDDLDRDDDLURLDRLDURUDRURDDDDDDULLDLDLU
LURLRUURDDLDDDLDDLULRLUUUDRDUUDDUDLDLDDLLUDURDRDRULULLRLDDUDRRDRUDLRLDDDURDUURLUURRLLDRURDRLDURUDLRLLDDLLRDRRLURLRRUULLLDRLULURULRRDLLLDLDLRDRRURUUUDUDRUULDLUDLURLRDRRLDRUDRUDURLDLDDRUULDURDUURLLUDRUUUUUURRLRULUDRDUDRLLDUDUDUULURUURURULLUUURDRLDDRLUURDLRULDRRRRLRULRDLURRUULURDRRLDLRUURUDRRRDRURRLDDURLUDLDRRLDRLLLLRDUDLULUDRLLLDULUDUULLULLRLURURURDRRDRUURDULRDDLRULLLLLLDLLURLRLLRDLLRLUDLRUDDRLLLDDUDRLDLRLDUDU
RRDDLDLRRUULRDLLURLRURDLUURLLLUUDDULLDRURDUDRLRDRDDUUUULDLUDDLRDULDDRDDDDDLRRDDDRUULDLUDUDRRLUUDDRUDLUUDUDLUDURDURDLLLLDUUUUURUUURDURUUUUDDURULLDDLDLDLULUDRULULULLLDRLRRLLDLURULRDLULRLDRRLDDLULDDRDDRURLDLUULULRDRDRDRRLLLURLLDUUUDRRUUURDLLLRUUDDDULRDRRUUDDUUUDLRRURUDDLUDDDUDLRUDRRDLLLURRRURDRLLULDUULLURRULDLURRUURURRLRDULRLULUDUULRRULLLDDDDURLRRRDUDULLRRDURUURUUULUDLDULLUURDRDRRDURDLUDLULRULRLLURULDRUURRRRDUDULLLLLRRLRUDDUDLLURLRDDLLDLLLDDUDDDDRDURRL
LLRURUDUULRURRUDURRDLUUUDDDDURUUDLLDLRULRUUDUURRLRRUDLLUDLDURURRDDLLRUDDUDLDUUDDLUUULUUURRURDDLUDDLULRRRUURLDLURDULULRULRLDUDLLLLDLLLLRLDLRLDLUULLDDLDRRRURDDRRDURUURLRLRDUDLLURRLDUULDRURDRRURDDDDUUUDDRDLLDDUDURDLUUDRLRDUDLLDDDDDRRDRDUULDDLLDLRUDULLRRLLDUDRRLRURRRRLRDUDDRRDDUUUDLULLRRRDDRUUUDUUURUULUDURUDLDRDRLDLRLLRLRDRDRULRURLDDULRURLRLDUURLDDLUDRLRUDDURLUDLLULDLDDULDUDDDUDRLRDRUUURDUULLDULUUULLLDLRULDULUDLRRURDLULUDUDLDDRDRUUULDLRURLRUURDLULUDLULLRD
UURUDRRDDLRRRLULLDDDRRLDUDLRRULUUDULLDUDURRDLDRRRDLRDUUUDRDRRLLDULRLUDUUULRULULRUDURDRDDLDRULULULLDURULDRUDDDURLLDUDUUUULRUULURDDDUUUURDLDUUURUDDLDRDLLUDDDDULRDLRUDRLRUDDURDLDRLLLLRLULRDDUDLLDRURDDUDRRLRRDLDDUDRRLDLUURLRLLRRRDRLRLLLLLLURULUURRDDRRLRLRUURDLULRUUDRRRLRLRULLLLUDRULLRDDRDDLDLDRRRURLURDDURRLUDDULRRDULRURRRURLUURDDDUDLDUURRRLUDUULULURLRDDRULDLRLLUULRLLRLUUURUUDUURULRRRUULUULRULDDURLDRRULLRDURRDDDLLUDLDRRRRUULDDD`
